version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    networks:
      - app_network
  app:
    build: app/
    ports:
      - "8000:8000"
    depends_on:
      - mongo
        # command: uvicorn main:app --host 0.0.0.0 --reload
    networks:
      - app_network
    restart: on-failure
    environment:
      DEBUG: 1
    volumes:
      - ./app/:/app
networks:
  app_network:
    driver: bridge
